init python:
    event('alexia_lends_a_hand', triggers="npc_events", conditions=("get_actor_job('alexia')=='forge'",), depends=('after_drinking_greyhides_alchol',), run_count=1, group='alexia_forge', priority=pr_npc)
    event('alexia_forge_flashing', triggers="npc_events", conditions=("get_actor_job('alexia')=='forge'", 'alGreyhideForgeSex == True',), run_count=1, group='alexia_forge', priority=pr_npc)
    event('forge_ABCs', triggers="npc_events", conditions=("get_actor_job('alexia')=='forge'",), run_count=1, group='alexia_forge', priority=pr_npc)
    event('andras_watches', triggers="npc_events", conditions=("get_actor_job('alexia')=='forge'",), run_count=1, group='alexia_forge', priority=pr_npc)
    event('greyhide_gives_back', triggers="npc_events", conditions=("get_actor_job('alexia')=='forge'",), depends=('after_drinking_greyhides_alchol',), run_count=1, group='alexia_forge', priority=pr_npc)


label alexia_lends_a_hand:

scene alexia_forge_1 with fade

"Alexia once again spent the week in the forge, helping out the blacksmith with his duties. This week, however, disaster had struck - there had been trouble on a number of routes between the mines and the portals back to the castle, meaning that numerous deliveries of iron were late."
"She spent most of her time cleaning and running errands, but as the week’s end approached, and more late deliveries began to pile up, there was still much to do."

scene bg22 with fade
show alexia forge neutral at midleft with dissolve
show greyhide neutral at cliohnaright with dissolve

gh "Is that all of the iron accounted for?"

al "I think so. I counted it as the orcs brought it in, and it seems about right. It is hard to tell with only estimates from the mines though."

gh "I see. Well at least it is finally here, but it doesn’t leave us much time to turn it into weapons and armour."

al "Perhaps we could get some more help?"

gh "I doubt it, and even if we could, orcs hardly make for the best assistants."

"Alexia smiled at him, but the minotaur did not smile back, he was deep in thought about how to deal with the current predicament. "
"The silence was broken by the sound of the door opening."

show andras displeased at edgeleft with moveinleft

an "Are my weapons ready, blacksmith?"

al "Not yet, there has been a delay because-"

"The demon turned to look at her and snarled."

an "Was I talking to you, woman?"

"Alexia looked down at the floor, as not to meet his eyes."
 
al "No…"

an "Then spare me your excuses."

gh "As Alexia was going to say before you so rudely cut her off, whelp, the deliveries were delayed, and as a result, I find myself behind."

an "I’m as interested in your excuses as I was in hers. I want those weapons by the end of the week, beast."
an "And if they aren’t ready, I’m sure there are plenty of old broken down minotaurs who can take your place when I snap your neck."

show alexia forge concerned at midleft with dissolve

al "Andras!"

"Andras ignored the woman’s protestations and turned to leave."

an "This week, Greyhide, or else."

hide andras with moveoutleft

al "I am so sorry, Greyhide, he shouldn’t talk to you like that."

show alexia forge angry at midleft with dissolve

al "It makes me so angry!"

"The minotaur smiled and placed one of his large hands on her shoulder."

gh "It is okay, child, others have said much worse to me."
gh "No minotaur is able to live as long as I have without enduring many, many, threats, believe me."

show alexia forge neutral at midleft with dissolve

al "Oh…"
al "Well, what do you propose we do? I doubt Andras was bluffing…"

gh "No, I suppose he was not. And even if he were, it would not do to fall behind with more deliveries due next week."
gh "Before we know it, iron will be piling up everywhere, and we can’t be having that now, can we?"

"He let out a laugh and then removed his hand from her."

gh "No, Alexia, we do the only thing we can do."
gh "We work."

scene alexia_forge_1 with fade

"They spent the rest of the day working hard, sweating amidst the heat generated by the castle’s furnace. Alexia would go and fetch iron as the inhumanly strong minotaur beat, shaped, and cooled various blades, plates, and other necessary elements for the needed equipment."
"Alexia would do her best to place together, or affix the pieces when he was done, as she had little skill at smithing herself. It took them all day, but by the end, it seemed like finishing over the next two days was a possibility, and that Greyhide’s head was probably safe. At least for now."

scene bg22 with fade
show alexia forge neutral at midleft with dissolve
show greyhide neutral at cliohnaright with dissolve

al "Phew… That should do it for today."

gh "Yes, I think we might even catch up at this rate. But I’m afraid the work will be just as bad tomorrow."

"Alexia smiled at him, in an attempt to allay his guilt. "

al "I don’t mind the work Greyhide, to be honest, it keeps my mind occupied so I don’t have to worry about my situation."

"The minotaur was silent, worried that he had inadvertently touched a sore point. Not everyone at the castle had chosen to come here after all. Alexia noticed his unease. "

al "Say, master Greyhide?"

gh "Hmm?"

al "I know I’m not much in the way of a smith, but maybe you could teach me how to make a blade?"

gh "There’s no shame in that child, I’m sure there are plenty of other things you are good at."

al "Well, I’m a pretty good dancer…"

gh "There you go, could you imagine me dancing? I’m sure you are much better at smithing than I am on my feet."

"She giggled, the idea of Greyhide dancing was quite funny, she had to admit."

gh "Maybe you can teach me one day, but for now, how about we try that blade?"

"The minotaur picked up a long tang and a pair of tongs and gave them to Alexia. She gripped the handle of the tang with the tongs and held it over the furnace until the end of the metal turned orange from the intense heat."

gh "Now, as you can see, the metal is currently too thick to make a decent blade, we need to draw it out."

al "That is what you are doing when you hit it with the hammer?"

gh "That’s right. Now, here, place it on the anvil."

"The redhead removed the tang from the forge and placed it on the anvil as instructed. The minotaur handed her a small hammer."

al "So, I just hammer it a few times?"

gh "Yes, the part where the metal is heated. Give it a good three or four hits. The metal will become thinner and lengthen, but it won’t grow any wider."

"Alexia lifted the hammer and brought it down a few times, as hard as she could."

al "Like this?"

gh "No, it requires more force. Here."

hide alexia
show greyhide neutral at center with moveinright
show alexia forge neutral at midleft with dissolve

"Greyhide moved behind her and wrapped his much larger hand around hers. Leading her firmly, but gently, he raised the arm again and brought the hammer down harder with the aid of his own strength."

gh "Like this. Now turn it over, otherwise, you’ll end up with ridges on the other side, and we don’t want that."

"The blade was now smooth, but being in such close proximity to the human was having an effect on Greyhide. The smell of her hair and the closeness of her body caused his loins to stir. With the two pressed together, Alexia could feel the huge, semi-hard member press against her back."

show greyhide neutral at edgeright with moveoutright

gh " I’m so sorry, Lady Alexia, I didn’t mean-"

al "It is okay, Greyhide. It is only natural."

al "If anything, I take it for a compliment! I feared you only fancied me after a couple of drinks. "

"She winked, hoping to diffuse the situation with a joke, but Greyhide’s expression darkened at the mention of the firegrout. "

gh "Lady Alexia, I… "

al "Shh, I know. "

if further_sex_scenes_with_greyhide == False:
    "She smiled understandingly at the minotaur. She could see he still felt bad about everything that happened back then."
    "Once Jezera’s interference was discovered, she and Rowan decided that it was all just the alcohol and magic talking, and that they would keep their relationship with Greyhide friendly. But now…"
    "Now with Greyhide’s towering figure before her eyes, his sweat and musk teasing her nose, and the heat of the forge mixing with the heat of her body, she wondered if she really wanted to stand by that decision. It felt like they made it so long ago…"

    menu:
        "Make a move on Greyhide, Rowan be damned":
            $ released_fix_rollback()
            "She rubbed her thighs together. Damn it, the thought of having that bull beneath her was making her hot. Usually, she tried not to think about it, but now..."
            "Ah, to hell with it!"
            $ change_corruption_actor('alexia', 5)
            jump helpForgeSex
            
        "Stay true to your promise with Rowan.":
            $ released_fix_rollback()
            show alexia forge concerned at midleft with dissolve
            "She shook her head slightly, banishing the nefarious thoughts that crept into her head. The decadent atmosphere in the castle was getting to her."
            jump helpForgeNoSex

else:
    "Luckily for Greyhide, Alexia and Rowan did not share his unease with regards to what happened. She already had Rowan’s permission to play with the minotaur, so all she had to do was assuage his fears… "
    
    menu:
        "Make a move on Greyhide.":
            $ released_fix_rollback()
            $ alGreyhideForgeSex = True
            $ change_corruption_actor('alexia', 5)
            jump helpForgeSex
            
        "She shouldn’t do anything without Rowan.":
            $ released_fix_rollback()
            "Alas, perhaps now was not the right time for that… "
            show alexia forge concerned at midleft with dissolve
            jump helpForgeNoSex


label helpForgeNoSex:

al "Do you want a moment to… Collect yourself?"

gh "Yes. Excuse me, my Lady."

hide greyhide with moveoutright

"She smiled warmly as he left the chamber. Another man would try to initiate something, but not Greyhide. Such a gentle soul… "

scene alexia_forge_1 with fade

"The issue dealt with, the two was free to return to work, without further accidents interfering with their schedule. Miraculously, they were able to meet Andras' quota, and Greyhide was able to avoid his wrath, much to the relief of both of them."

return



label helpForgeSex:

al "There is nothing to be ashamed of Greyhide. Besides..."

"Alexia put the tang down on the anvil and took a step towards the minotaur, flashing him a coy smile."

show alexia forge neutral at midright with moveoutright

al "The feeling is mutual."

gh "Alexia, I don’t think-"

al "Shhh."

#cg1
scene cg315 with fade
show alexia forge neutral behind cg315
show greyhide neutral behind cg315
pause 3

"She took a few more steps until she was before him. With how much taller the minotaur was, she didn’t even have to kneel as she freed his huge phallus from his pants."
"He began to protest, but Alexia shushed him again, as she gently stroked his cock with both of her hands, coaxing it to full hardness."   

al "You just let me take care of everything, okay?"

"She had felt the minotaur’s cock before, but she had yet to taste it, and even though it was far too large to ever fit in her mouth, that wasn’t going to stop her."
"Leaning slightly down she was hit with a strong animal musk, almost overpowering, and nothing like the smell of that of a human. It only served to make her more curious about how the beast would taste."
"Continuing to stroke the shaft with both hands, Alexia softly kissed the top of the minotaur’s massive prick, before beginning to lick it. Like the smell, it had a strong taste, one that she did not find unpleasant."  
"Greyhide let out a grunt of pleasure as she continued to run her tongue around his member, coating it with her saliva. After all, it would have to be very lubricated for what she intended to do once she’d finished enjoying the taste of his cock."
"The pleasure had caused Greyhide’s initial apprehension to dissipate, as he no longer objected to Alexia’s ministrations. He watched eagerly as the human woman worshipped his huge bull dick."
"She continued to hungrily lick, tongue, and kiss it all over as she stroked. Then suddenly, she stopped and stood back straight."

al "Now, lie down."

gh "Huh?"

al "All this foreplay is fine, but there’s nothing like the real thing."

"Greyhide looked at her as it dawned on him what she intended, worried."

gh "But Alexia, you can’t! It is too big."

al "Perhaps, but I certainly aim to try, so be quiet and lie down."

"The minotaur knew when he was beaten and did as he was told. The redhead removed her clothes and positioned herself above him. She spread her legs as far as she could, and begin to lower herself down onto the giant prick below her."

#cg2
scene cg282 with fade
show alexia necklace naked aroused behind cg282
show greyhide neutral behind cg282
pause 3

"It wasn’t going to be easy, that was for sure, but the poor minotaur hadn’t had proper sex since his lover had died, and Alexia was determined to do the best that she could to help on that front."
"It took some work, and a lot of lubrication, but she was able to work the huge tip of the minotaur’s dick past the opening of her snatch." 
"That alone was enough to make her feel almost full enough to burst, but she wasn’t finished. She started to slowly and surely push herself down, taking as much inside her as she could."
"Once she reached her limit, she lifted herself up again and then did the same. It took a while, but eventually, she was able to get a good rhythm going, as the minotaur groaned and grunted below her."
"She felt impossibly full as she ground her hips up and down, moaning loudly as she did so."

al "Gods, it is so big, I didn’t think…"
al "Hnnn!!"

"Alexia felt a long way of orgasmic bliss hit her as she impaled herself on his dick. It throbbed inside her against her walls.  The minotaur was close too."

gh "Alexia, I’m... I’m…"

if all_actors['alexia'].corruption < 31:
    al "That’s it, Greyhide, cum with me… Uhhh…"

elif all_actors['alexia'].corruption > 30 and all_actors['alexia'].corruption < 61:
    al "Oh fuck yesss…. Cum!!!"

else:
    al "Fuck Yes!! Breed me, you beast!!"

#cg2 - cumshot
show cg282 with sshake
show cg282 with sshake
scene cg283 with flash
pause 3

show greyhide neutral behind cg283

"Greyhide let out a loud bellow, shuddered and unleashed his seed deep within her. His load was far larger than that or a human, and when his cock plopped out after cumming, jizz leaked from Alexia’s gaping cunt."

show alexia necklace naked behind cg283

al "Oh dear, it looks like you have made quite the mess."

gh "I’m sorry, I didn’t intend…"

al "Shh, you."

"She kissed him softly on his snout."

al "Everybody gets lonely, we all have needs. "
al "You’ve been on your own for a long time, and I wanted to do something to help you. That is all there is to it, so there is no need for none of your typical moodiness about this, okay?"

"The aforementioned typical moodiness on his face transformed into a smile."

gh "Yes… Thank you Alexia."

"Alexia stood up and picked up her clothes from where she had discarded them nearby."

if further_sex_scenes_with_greyhide == True:
    al "And if you’re still unconvinced… Next time I’ll invite Rowan along, so we can hammer the point in together. "
    gh "Lady Alexia, please. I am not worthy of such friends. "
    al "I think you’re the only person in this castle that truly understands the meaning of this word. You give yourself too little credit Master Greyhide."

al "Now, we’d better get back to work. It wouldn’t do for you to lose your head because I decided to take advantage of you."

scene alexia_forge_1 with fade
"Alexia smiled warmly, and once again assured him that it was fine. The rest of the day passed with a small amount of awkwardness, but the rest of the week was free from incident."
"The pair were able to catch up, sparing Greyhide from Andras’ wrath, much to the relief of the both of them."
return

####################################################################################################################
####################################################################################################################
####################################################################################################################

label alexia_forge_flashing:

scene bg22 with fade
show alexia forge neutral at midleft with dissolve
show greyhide neutral at cliohnaright with dissolve

"Alexia entered the sweltering abode of the Castle’s resident blacksmith that afternoon with an equally warm feeling in her tummy. The forge was already blisteringly hot, and Alexia found herself wiping sweat from her skin almost before she’d even stepped into the Minotaur’s abode."
"Greyhide was at his usual place, hammering a breastplate into shape with long, slow strikes of his hammer upon the anvil. He gave her a short nod before returning to his work, his face tense with concentration. She threw on her apron and moved to help him at the bellows."
"She was huffing and puffing as she did her best to pump the cumbersome device, feeding the fire for the grim Blacksmith to ply his trade. Every so often Greyhide pause with the item he was hammering, examining it with a critical eye before sticking it back into the forge to heat before working on it further."
"Alexia found it difficult to pay attention today. She kept stealing glances in the direction of Greyhide, her eyes trailing across his thick biceps, the clear outline of muscle on his body as he lifted and struck the hammer in repetition." 
"There was something so… {i}masculine {/i} about him. The way he moved, the way he worked..."

show alexia forge aroused at midleft with dissolve

"Memories of his thick hands around her made Alexia start to lose focus. Her thighs clenched as she found herself getting horny, despite the heat and stuffy climate."

gh "Why did you stop pumping?"

show alexia forge shocked at midleft with dissolve

al "What? Oh! I-"

"She’d been so lost in her own thoughts, Alexia had stopped working the bellows. Greyhide had ended his striking and was looking at her with an expression that was part irritation, part confusion."
"Alexia resumed her pumping, doing everything she could to ignore the heat in her chest and the dampness of her loins. She tried to focus, her brow clenching as she pumped as best as she could." 
"She had barely improved at all since she’d started working with Greyhide, but at least she’d found some solace in his companionship."

"The thought of “companionship” made her think back once more to their previous illicit encounter. He’d been so strong, so {i}powerful{/i}."
"Alexia felt her fingers slip free from the handle of the massive bellow, deflating it with a slow, flaccid huff of air. She turned to Greyhide, now {i}far{/i} too distracted to continue her work."

show alexia forge aroused at midleft with dissolve

al "Hey… can we talk for a minute?"

"Greyhide regarded her for a long moment, quirking an eyebrow. With a heavy sigh he set aside his hammer, turning to face Alexia and folding his arms together. She couldn’t help but stare at his fur, glistening in the light of the forge."

gh "We can. It does not seem we will get much work done today."
gh "What’s on your mind?"

al "You."

"The bulky Minotaur paused, then broke out into a small smile."

gh "You are odd, Alexia."

al "...And you’re not?"

"Alexia smiled her eyes lidding low as she tugged at her apron. The Minotaur watched her as she undid her top and exposed the pale skin of her chest. She relished in the sight of his trailing gaze as it moved down to stare in open interest at her exposed cleavage."

al "I haven’t forgotten what you feel like."

gh "...Nor I you."

"Alexia took a step towards him, swaying her hips as her eyes lidded low."

al "What say we forge something a bit different today, you and I? Your hands must be tired."

"Alexia could see the conflict in his eyes; the way he looked at her, the way his groin stiffened, she knew she was having the desired effect. Alexia jiggled her breasts in an effort to entice him."

gh "It is difficult to say no..."
gh "But I cannot stop my work.  There is too much to do. The whelp will not be pleased if I am late."

show alexia forge angry at midleft with dissolve

"Alexia let out a discontented huff, her heart sinking at the unfulfilled expectation of further fornication with the burly blacksmith. The Minotaur took a last, long look at Alexia’s cleavage and let out an appreciative rumble."

gh "Such a soft, delicate thing, to have teats like yours."

al "You would know."

gh "Yes, I would. Now back to the bellows."

return

####################################################################################################################
####################################################################################################################
####################################################################################################################

label forge_ABCs:

show bg22 with fade
show alexia forge neutral at midleft with dissolve
show greyhide neutral at cliohnaright with dissolve

al "Okay, now what is the next symbol?"

gh "This is pointless."

al "Come on, don’t give up! You’re doing so well."

#greyhide angry

gh "You’re a poor liar, little one."

al "No, I’m serious!"
al "Now focus: what does the next symbol mean?"

"Alexia lifted the book, holding it up to the Minotaur’s nose so he could see. She was seated on a small stool, with Greyhide standing over her shoulder."

gh "Hrmm…"

"The Minotaur’s brow furrowed with concentration, his flat tongue clicking against the tip of his mouth as he considered. Alexia smiled in encouragement."
"The dour blacksmith’s illiteracy had come into stark focus for her a few days ago, after she saw him absentmindedly sign off on the latest supply shipment without realizing the load was far less than expected."
"Rather than checking the manifest and then signing his name, Greyhide instead swept his quill across the paper in a single, careless stroke and handed it back to the courier."
"Two days and several unfulfilled orders later, and Alexia realized that his inability to read was hampering Greyhide’s work. She took it upon herself to tutor him."
"It took some cajoling on her part to get him to agree to the impromptu lesson. But the stubborn Blacksmith at last relented after Alexia gave him a particularly piteous doe-eyed look."
"Now here she sat, like a schoolteacher with an impetuous pupil, half distracted and utterly disinterested in the lesson material."
"Still, Alexia was determined to succeed."

#greyhide neutral

al "Come on Greyhide, what does the symbol mean?"

gh "It looks like a dead worm drying in the sun."

al "Uh, yeah. I guess it does..."
al "And, what else has the shape of a worm? What kind of animal?"

"Greyhide’s nose crinkled with thought."

gh "A snake?"

show alexia forge happy at midleft with dissolve

al "Yes! Perfect! A Ssssssssnake! What sound does the ssss-ymbol make then?"

"Greyhide stared at her with a deliberately blank expression, as if she had just said something incredibly stupid. A self-conscious blush spread across Alexia’s cheeks."

gh "You are strange, Alexia. Even for a human."

show alexia forge angry at midleft with dissolve

al "Come on, I’m practically giving you this one!"

#greyhide angry

gh "If this is a gift, then I’d prefer the punishment."

al "Come on you old bull, you can’t be {i}that{/i} stubborn."

#greyhide neutral

gh "Stubbornness isn’t the problem. You’re asking a fish to learn how to fly."

show alexia forge happy at midleft with dissolve

al "Unlike the fish, {i}you{/i} can learn to read."

"Greyhide let out an annoyed huff of air, expelling it in one large breath from his nostrils."

#greyhide neutral

gh "I don’t think so."

show alexia forge neutral at midleft with dissolve

al "Come on, at least give it a try. What harm could it do?"

gh "Runes on paper won’t help me forge my weapons."

if alGreyhideForgeSex == True:
    "Alexia’s eyebrow quirked, she gave him a knowing look."
    al "…Neither does sheathing your “sword” inside a tiny human. Do you plan to give up on that as well?"
    "Greyhide chuckled, putting a large hand upon her shoulder and patting it."
    #greyhide happy
    gh "Maybe. We’ll see."
    
show alexia forge concerned at midleft with dissolve

al "Just one more try? For me?"

"Alexia did her best to put on a pathetic, puppy-dog face. She smiled inwardly in triumph when the grim blacksmith let out a hefty sigh."

#greyhide neutral

gh "..Fine. What sound does the little worm make?"

show alexia forge neutral at midleft with dissolve

al "The same sound you make when you say the word ssssnake: “Ehss.”"

gh "“Ehss.”"

show alexia forge happy at midleft with dissolve

al "Now you’re getting it!"

show alexia forge neutral at midleft with dissolve

al "-So if that makes the “Ehss” sound, and you already guessed the previous symbols…"
al "Then all you have to do now is put the sounds together!"

"Greyhide stared at the letters, squinting his large eyes as if to narrow his view exclusively to the tiny scribble on the page."

al "Here, let me start you off:"
al "Puh-aah-"

gh "Sssss-oaaarrp"

show alexia forge shocked at midleft with dissolve

al "...What?"

gh "Sorp. The word is sorp."

"The word was {i}Pass{/i}. Alexia stared at the letters on the page in a vain attempt to understand the impatient Minotaur’s reasoning. "

show alexia forge concerned at midleft with dissolve

al "You’re… close. But the “Ehss” is at the end."

gh "No, it’s at the beginning."

"Alexia ran her finger back and forth beneath the word, underlining each letter with her fingernail."

show alexia forge neutral at midleft with dissolve

al "No, see: you read it from left to right."

gh "I did read it that way. The word is Sorp."

show alexia forge shocked at midleft with dissolve

al "...it’s “Pass.”"

#greyhide angry

gh "No, the word is Sorp."

"Acting as if that settled the matter, Greyhide turned to the table next to him and picked up his blacksmith's hammer that he’d set aside for the sake of the lesson."

#greyhide neutral

gh "Come. Enough runes for the day. We have work to do."

"Greyhide folded his arms together and straightened his back, lifting his chin as if daring her to disagree."

"Was… was he {i}intimidated{/i} by reading?"

show alexia forge neutral at midleft with dissolve

al "Just a minute more, please."
al "I want to see why you’re having trouble with the word."

#greyhide angry

gh "I’m not having trouble. The word is Sorp."

al "The word is {i}Pass{/i}. You’re saying it backwards."

gh "Words are words, but work is work. We have much to do."

show alexia forge concerned at midleft with dissolve

"A strange thought entered her mind. Alexia held up the book, pointing at another word on the list."

al "One more word, and then we can get back to work."

"Greyhide stared at her for a long moment, then let out a long-suffering sigh. He put down his hammer again and peered at the page."

#greyhide neutral

gh "P-puh…"

show alexia forge shocked at midleft with dissolve

"Alexia’s eyes widened. He was doing it again."

gh "puh… aah… ess."
gh "P-Pass?"
gh "The word is Pass."

#greyhide angry

gh "That is the word from before. You mixed up the words. That’s why you thought I was saying Pass."

"Alexia stared at the page in disbelief. The word she’d shown him this time wasn’t pass, it was {i}sap{/i}."
"Greyhide read words backwards!"

#greyhide neutral

gh "Enough runes now. We have work."

"Greyhide let out a snort of air and retrieved his hammer, lumbering over to his place at the forge like a sullen child being disciplined."

show alexia forge neutral at midleft with dissolve

"Alexia stared at the book for a long moment, reading the two words he’d tried and failed to comprehend over and over to be sure of what she’d just heard."

gh "You coming?"

"Alexia’s head snapped up from the book. Greyhide’s face was flat and expressionless. She snapped the book shut and stood up off the stool."

al "Y-yeah…"

gh "Good. The floor needs cleaning. See if those reading runes help your sweeping technique."

return

####################################################################################################################
####################################################################################################################
####################################################################################################################

label andras_watches:

scene bg22 with fade
show alexia forge neutral at edgeleft with dissolve

"Morning at the forge. The sound of Greyhide’s hammer against molten metal sang out in a constant, thumping beat." 
"The almost hypnotic rhythm of the Minotaur’s labors reminded Alexia of an old tune from Arthdale. She hummed it to herself in time to the ringing of his work as she descended the stairs into the forge."

show alexia forge happy at edgeleft with dissolve

al "Hmm hmm, hmm {i}hmmmm{/i}!"

show alexia forge shocked at edgeleft with dissolve

al "Hm?"

"She stopped short at the foot of the stairs, caught off guard at the strange sight in front of her."

show greyhide neutral at center with dissolve
show andras displeased at edgeright with dissolve


"Standing near the wall at the base of the stairs was Andras. His arms were crossed, his eyes trained with burning intensity to the sight of Greyhide working."
"It was as if Andras were attempting to burn a hole though Greyhide’s hammer with his gaze alone."
"Greyhide, for his part, paid no heed whatsoever to the Demon lurking on his periphery. He moved as he always did: with calm surety and confident strikes."
"The Minotaur dipped the white blade into the water barrel, a hiss of steam rising from the dispersed heat. He lifted it out of the water, inspecting the metal for a moment. He let out a gruff snort and set the weapon aside."
"Andras watched every motion, his eyes never wavering, his attention focused utterly on the old Blacksmith."

show alexia forge concerned at edgeleft with dissolve

"Alexia paused, frozen to the spot by the odd sight. Had Andras been looking at her with that kind of unblinking intensity, she’d have dissolved into a puddle of nerves."

if NTR == True:
    "...Or perhaps a puddle of something else."

"She didn’t know quite how to proceed. Andras was standing right next to the stairs. Surely he’d see her enter?" 
"The last thing she wanted to do was to draw his ire, and she was uncertain of his motives for watching Greyhide work. Would she be interrupting his obtuse concentration?"
"She almost asked him what he was doing there, but then thought better of the idea. When Andras didn’t want to be disturbed, he made it quite clear to everyone around him."
"This was clearly one of those times."

show alexia forge neutral at edgeleft with dissolve

"Alexia let out a heavy sigh. She had a job to do, and Greyhide was counting on her. If she {i}had{/i} to interrupt his queer reverie, then so be it. At least she wouldn’t let down the forgemaster."
"Steeling herself, Alexia descended the final steps and strode into the smithy. It took every ounce of courage to not glance in Andras’ direction as she passed him."
"The Demon made no sound of disapproval at her sudden presence. He made no sound at all in fact, acting for all the world like a glowering, immovable gargoyle looming in the corner of the room."

#greyhide happy

gh "Good morning, little one. Are you ready to work?"

"Greyhide smiled at her like he always did, paying no heed whatsoever to Andras’ glare."

show alexia forge happy at edgeleft with dissolve

al "Y-yeah!"

gh "Good. The forge is getting a little cold. Could you fetch me more coals?"

al "Of course."

"Alexia hurried to the task, casting a final glance at the unnerving expression on Andras’ face before continuing."
"It went like that for the better part of the day: Greyhide busying himself with his work, Alexia helping wherever she was needed, and Andras acting as a silent sentinel over the proceedings."
"As time passed, Alexia grew more comfortable with the awkward guest in the room, eventually forgetting he was there at all."

hide andras with dissolve

"It was only after several hours of hard work in the forge that she glanced up, and realized the Demon was gone."

show alexia forge shocked at edgeleft with dissolve

al "W-"
al "Where did he go?"

#greyhide neutral

gh "Who?"

show alexia forge concerned at edgeleft with dissolve

al "Andras! He was watching us this whole time."

gh "The whelp?"

"Greyhide let out a gruff chuckle."

gh "I forgot he was there. He does this sometimes."

show alexia forge shocked at edgeleft with dissolve

al "He… watches you?"

"Greyhide shrugged, his rippling shoulder raising and lowering as he wiped the sweat from his brow."

gh "Pay him no mind, Alexia. We have work to do."

show alexia forge concerned at edgeleft with dissolve

al "But… why does he do that?"

"Greyhide’s blank expression was his only real answer."

gh "Does it matter?"

"Alexia stopped herself before she could say more. There was a strange wisdom in that simple question."

show alexia forge neutral at edgeleft with dissolve

al "I… suppose not."

gh "Good."
gh "The forge is getting cold again. Would you please fetch me more coal?"

"Alexia hurried to the task, her mind twisting with the twin mysteries of Andras’ actions and Greyhide’s indifference."

return

####################################################################################################################
####################################################################################################################
####################################################################################################################

label greyhide_gives_back:

scene bg22 with fade
show alexia forge aroused at midleft with dissolve

"By all the Saints in Solansia, Alexia couldn’t take it anymore."
"She’d been struggling with this warmth in her tummy now for what felt like days, an unending deluge of desire and horny feeling coiling like a python in her chest." 
"She felt pent up, like a restless wild colt trapped in a too-small pen."

if alexiaJezObedient == True:
    "Jezera had been caught up in the intricacies of her job as the true ruler of Bloodmeen. Despite brief glimpses of her the last few days, she had been all but a ghost."

elif alexiaAndrasObedient == True:
    "Andras was off gallivanting around the countryside with his soldiers once more. He had left her with a parting gift: two days of solid edging before he departed with nary a goodbye."

else:
    "Rowan was gone from the castle, and had been for almost four days. He wouldn’t be back to help her for another three."

"It was no different than any other week, yet as far as her body was concerned, she’d been stranded out in a sexual desert for months with no relief, and she was slowly dying of thirst."
"It was this profoundly frustrated Alexia, starved of company (and of a particular, masculine “attention”) who walked into Greyhide’s forge with sex on the mind and a damp patch on her panties."

al "...Morning Greyhide."

show greyhide neutral at cliohnaright with dissolve

"Greyhide, in a manner most unlike him, was sitting idle next to his anvil, lounging in his chair, shirtless. A thin sheen of sweat covered his coarse brown fur, a result of the simmering heat of the forge."

gh "Good morning, little one. No work here, today."

"Alexia let out an annoyed sigh. As difficult as forgework could be, it was an excellent way to get one’s mind off of her present… difficulties. The exhausting work did wonders for her pent up energy as well."

show alexia forge angry at midleft with dissolve

al "What?! Why?"

gh "The latest shipment is late. Won’t be here till late afternoon. By then it will be too late to start."

"Alexia couldn’t help but notice the casual flex of his muscles as he leaned back in his chair. Greyhide, despite his age, was the very image of masculine power."

gh "There’s little to do but wait. You may go. I have nothing for you today."

show alexia forge aroused at midleft with dissolve

"Alexia shifted back and forth on her heels. The more she looked at Greyhide, at the casual way he sat in front of her, cool and confident as a bull, the more she realized she wanted him."
"Their precious exchanges had been… {i}more{/i} than pleasing. And the Minotaurs barrel chest and firm expression sent tiny butterflies in roiling circles in her belly. Her face reddened, her eyes drawn downwards towards his shorts."

al "A-actually, I wouldn’t mind it if we just… talked for a minute."

"The Minotaur’s brow furrowed with confusion at her odd behavior."

gh "Are you all right?"

show alexia forge shocked at midleft with dissolve

al "I-I’m fine! Why do you ask?"

gh "You’re staring at me."

show alexia forge aroused at midleft with dissolve

"It was true. The bulge in his crotch was calling to her. She had seen the Minotaur’s mammoth pole before. Dangerous, delectable thoughts and lurid images ran like lightning through her mind."

if all_actors["alexia"].corruption < 31:
    "Greyhide’s bare body, exposed to her in the flickering light of the forge. His bulging, muscled body stooped at the anvil as he worked."
    "She could see every curve and facet of his body as he moved, a peculiar adonis in the midst of mascluine work."
    "Alexia, naked as well, working next to him, the heat of the forge reflecting the heat in their bodies. Sweaty, steaming forms coming together in a brief moment, pressing close as his hands drifted downwards to-"
    
else:
    "Greyhide, stripped naked, bending her helpless form over an anvil, striking her ass with his large hands in imitation of the hammer blows on molten metal."
    "Forging her into a wanton, wet slut the same way he’d forge a masterwork weapon."
    "Her fingers reaching out, cupping his large furry balls in hand as she milked him of his seed, staring up into his bovine eyes as she let out a whorish moo-"
    
show alexia forge shocked at midleft with dissolve

gh "{i}Alexia!{/i}"

"Greyhide’s sudden shout made her nearly jump out of her skin. His eyes were fixed to hers, a contemplative look coming to the old Minotaur’s face."

al " I-I…"

gh "You have not heard a word I said."

show alexia forge concerned at midleft with dissolve

al "I’m sorry Greyhide, I just…"

"If there was anyone who could be honest with regarding her plight, it’d be Greyhide. Alexia let out a long sigh."

show alexia forge neutral at midleft with dissolve

al "I’m just frustrated. Rowan hasn’t been around much lately, and I’m a bit…"

show alexia forge aroused at midleft with dissolve

al "Lonely."

"Greyhide let out a soft grunt, shifting position in his tiny chair. Alexia gulped when she saw his thick arms flex."

gh "Lonely, is it?"

show alexia forge angry at midleft with dissolve

al "I never took you for the sarcastic type, Greyhide."

show alexia forge aroused at midleft with dissolve

al "Honestly, I was looking forward to a long, hard work day in the forge to get my mind off things."

show alexia forge neutral at midleft with dissolve

al "...But I guess that’s no longer an option, is it?"

gh "Forge work? No."

"The Minotaur shook his shaggy mane back and forth."

gh "But there is something else you can do."

"Alexia rolled her eyes."

show alexia forge angry at midleft with dissolve

al "If there was, I’d have done it already."

"Greyhide chucked, a deep rumble in his throat that brought an unconscious blush to Alexia’s face."

#greyhide happy

gh "You’re a strange one, Alexia; I’m offering to help you."

show alexia forge shocked at midleft with dissolve

al "How would you-"

show alexia forge aroused at midleft with dissolve

"Greyhide stood up out of his chair, looming over the tiny human in his midst with his rippling bulk. He was so big, his hands alone could grab the whole of her ass in one, meaty palm."
"He looked down his nose at her, letting out a heavy snort that blew her hair back. She blinked in surprise as he stepped into her personal space."
"Strange… he was so imposing, standing over her like a bull ready to charge. Yet, she didn’t feel an ounce of fear. She trusted him utterly."

gh "How do you want me to help?"

menu:
    "Tell him to remove your clothes.":
        $ released_fix_rollback()
        pass
        
    "Tell him it is nothing.":
        $ released_fix_rollback()
        al "It's uh.. nothing really, I should get back to work."
        hide alexia with moveoutleft
        "With that she dashed off, leaving the minotaur standing alone, and confused."
        gh "Humans are such strange creatures."
        return

al "...Take off my clothes"

show alexia necklace naked aroused at midleft with dissolve

"He reached down, pulling her apron off of her in a single, smooth jerk."

gh "Done."

show alexia necklace naked shocked at midleft with dissolve

al "W-wait!"

"Her timid tone gave the Minotaur pause. He stopped short, his thick fingers hovering near the buttons on her shirt."

gh "Why?"

show alexia necklace naked at midleft with dissolve

al "It’s more than just a mindless rutting that I’m looking for. I’m looking for passion, for {i}foreplay{/i}, do you understand?"

gh "Foreplay, I have heard you say that word before. But I do not know it."

"Alexia suppressed a groan. How could someone as clever as Greyhide be so dense, sometimes!"

show alexia necklace naked aroused at midleft with dissolve

al "I want to fuck you, Greyhide, but I want to {i}please{/i} you, too."

gh "Fucking {i}is{/i} pleasure, little one."

show alexia necklace naked at midleft with dissolve

al "Yes, but… "
al "Solansia forgive me, how am I supposed to explain this? "
al "When humans mate, they do more to each other than just hump."

gh "So I’ve noticed, little one. You can be quite creative when you wish to be."

show alexia necklace naked aroused at midleft with dissolve

"She took Greyhide’s hand in hers, stroking the thick digits of his fingers as she looked deep into his eyes."

al "Sometimes, a mate wants to service her lover. I want to be pleased, Greyhide, and to please you in return."

show greyhide sad at cliohnaright with dissolve

gh "I would like that too. But…"
gh "I do not wish to hurt you."

al "It doesn’t have to be that."
al "Here, let me show you."

"Alexia put her hands upon his thick chest, marveling at the iron-like feel of his corded muscles." 
"Her cheeks reddened as she glanced downwards and saw the growing bulge beneath his loincloth."

"Sit down."

#cg1
scene cg586 with fade
show alexia necklace naked aroused behind cg586
show greyhide neutral behind cg586
pause 3

"Alexia reached out, peeling on the fabric of Greyhide’s loincloth as the head of his fat, pillar like cock poked out the top. Cooing, Alexia pulled the useless clothing off of him, exposing his growing erection and his large, furry testicles."
"She took his manhood in hand, marveling at the virile blood flow as the thing thickened and swelled in her hands. She planted a soft kiss upon the shaft, moving upwards as like climbing the rungs of a ladder."

al "{i}Mwah!{/i}"
al "I want that. I want us to please each other… and maybe you can do the same to me."

"Greyhide let out a low grumble in his throat. He leaned back in his chair, angling himself so Alexia would have to stand to reach the pinnacle of his throbbing erection. His large, cowlike eyes shined with amusement."

gh "I have never done this before. You must show me, little one."

"Alexia obliged. The raging fire in her belly wouldn’t let her do anything else. She planted a kiss upon the very base of his cock, her hands reaching down to cup his balls."
"She handled them like priceless eggs, gently rolling them in her fingers as she bent her neck upwards to resume her long ascent."
"Alexia stuck her tongue out, planting it against the bulging vein of the cock that she knew - it she played her cards right - would be the primary vehicle through which he’d shoot his cum all over her."
"Delighted by the deliciously naughty thought, Alexia suckled upon it, working her hips this way and that as she drew a ragged line of saliva up the turgid pillar. At last she reached the head, moaning and licking he cumslit and planting soft kisses everywhere."
"Her panties were damp mess, her legs trembling from the effort of holding herself up as she bent over the grunting Minotaur, working his thick dick into a lather with her hands."

al "Do you like that, Greyhide?"

scene bg22 with fade
show alexia necklace naked aroused at midleft with dissolve
show greyhide neutral at cliohnaright with dissolve

"The old blacksmith let out a snort. The closet thing the stubborn oaf could ever get to an honest admission. She chuckled and stood up, her cheeks burning and her face a red mess."

al "Now it’s your turn. Plant your hooves, I’m going to climb on top of you."

"Greyhide, his eyes still fixed upon her, did as he was bid, spreading his legs wide and leaning back so that the chair was propped against the anvil, giving an ideal angle for Alexia to clamber on top of him and sit in his lap." 
"She giggled as she felt the meat of his shaft propping her up from behind, a stiff reminder of his attraction to her. Greyhide put a large hand against her back, trailing down to grope her bottom."

gh "What now, hm?"

"His voice was deep, a masculine rumble that made Alexia’s head spin and her knees weak. She put her hands to his chest, reveling in the thick, masculine scent he exuded."

al "Now… you try."

gh "Try what?"

al "I licked you, now you lick me."
al "Have you never wondered what I taste like?"

gh "...Taste like?"

"Alexia laughed. He was stubbornly charming, the old stick in the mud. "

al "You {i}must{/i} know what I mean, Greyhide. Haven’t you ever tasted a woman…"

#cg2
scene cg587 with fade
show alexia necklace naked aroused behind cg587
show greyhide neutral behind cg587
pause 3

"She took his hand and led it to her crotch. His meaty fingers made short work of her panties, spreading her pussy wide as one slipped in with a soft, wet {i}squelch{/i}."

al "{i}Aah{/i}!"
al "H-have you ever tasted one… there?"

gh "No."

"His voice was gruff, but there was a deep, erotic curiosity in his tone. Alexia smiled at him, running her fingers across the side of his face."

al "Good. Then I’ll be the first."

"Greyhide let out an appreciative rumble. Alexia squeaked in surprise when she felt his hands reach down to grab her by her hips."
"He manipulated her like a doll, lifting her with his prodigious strength and spinning her about. He planted her stomach on his chest, giving him easy access to her nethers."
"Alexia gasped when she came face to face with Greyhide’s erection once more. It stared back at her, pulsing with a hot, masculine energy. Her face reddened."
"Greyhide peeled her clothing off of her with a simple rip of the fabric. Alexia let out an ecstatic squeal of pleasure, followed by a moan as the large Minotaur spread her asscheeks apart."

gh "...What should I do?"

"Alexia - wet, wanton and nearly crazed with lust - let out a sultry moan and took the Minotaur’s dick in hand once more."

al "Lick it. I want you to {i}taste{/i} me!"

"She resumed her horny worship, licking and kissing every spot she could find. If she were braver, she’d have tried to take his massive length in her mouth, but the sheer geometry of the challenge was too much to overcome."
"Such minor triflings were rendered moot when she felt the warm, fat tongue of the Minotaur press up against her drooling slit."

al "{i}Aaaan{/i}! Solansia preserve me!"

"His tongue was large and flat, a wet, spongy surface that set the nerves of her pussy afire. She waited with bated breath for him to start a rough tonging session."
"But… nothing happened. His tongue was pressed to her pussy, but it stayed in place like a horse at a salt lick."
"Breathless, red faced and trembling, Alexia cast her gaze back at Greyhide. His brow was furrowed, his eyes focused on the task. He tried to say something through the confines of her crotch."

gh "{i}Ampf fi doing it righth{/i}?"

"Alexia lifted off the Minotaur for a moment, sitting up on his chest. She reached back and took him by the scruff of hair between his horns."
"Then, without preemption, she jammed him nose-first into her ass."

al "Lick me, lick me! Get as {i}deep{/i} as you can!"

"The Minotaur complied, lapping at her sodden cunt with long, slow drags of the tongue. Alexia shivered in place, feeling the flat weight of him sliding across her lips as a wide, dopey smile crossed her face."

al "{i}Mmmh.{/i}"

"She lowered herself down once more, redoubling her efforts as she kissed and suckled on every unpolished spot of Minotaur dick she could find. Greyhide grunted when she planted her lips on his cockhead and rolled her tongue around the rim."
"Greyhide - novice that he was - made up for his inexperience with sheer enthusiasm. His fat tongue managed to lick the whole of Alexia’s wet hole from stem to stern in a single languid movement."
"He was slow, but steady, managing to slip the edges of his flat tongue inside of her and wiggle around inside. Still more nerves touched off in Alexia’s head, and she found herself rolling her hips against his face in an effort to encourage him."
"It all built up to this penultimate moment. Feeling the rising tide of an orgasm coming on, Alexia took matters into her own hands… literally."
"She latched her hands around the base of Greyhide’s cock and jacked him roughly, planting sloppy kisses to his head and shaft all the while."

gh "{i}Grrh!{/i}"

"Greyhide keyed in to Alexia’s attention, lapping hard at her clit and cunny up and down in maddening repetition"

#cg2 - var 1
scene black with fade
show alexia necklace naked aroused behind black
show greyhide neutral behind black

"She gasped and trembled and came all over his face, her spraying wetness coating his lips and snout as he licked her to completion."
"Greyhide was not long in following her. His balls clenched, a thick tide of Minotaur spunk surging upward through her clenched fingers to the top. She planted her lips upon his cumslit in the vain endeavor to take it all down her throat."
"He pulsed once, spurting a mouthful of his seed down her throat as she gulped down what she could. The second pulse proved too much for her, and her cheeks bulged."
"Cum spurted out from the edges of her lips and dribbled down the sides of his cock in pearlescent channels."
"A third pulse, and Alexia was overwhelmed, pulling her lips off of his fecund cock as it sprayed a fertile line of white up over her head, coating her face, lips and back in a line. "
"Alexia trembled, feeling Greyhide’s relentless tongue sliding across her clenching pussy. His hands spread her ass wide, kneading at her skin as he licked her well past his own orgasm."
"Alexia continued to jerk him, draining the last of his seed out onto her tongue as a wave of supreme bliss flowed over her."
"Six hells, she’d needed this."
"The two reveled for a moment in their shared pleasure. Alexia grinded her hips into Greyhide’s slow, licking tongue, and she in turn licked up the stray cum leftover on his cock and belly."
"Once she had finished cleaning him up, she reluctantly pulled herself off of him."

scene bg22 with fade
show alexia necklace naked aroused at midleft with dissolve
show greyhide neutral at cliohnaright with dissolve

al "So… how was it?"

gh "Different. Very different."
gh "Your pussy tastes good, little one. "

al "I’m glad you approve. You don’t taste so bad yourself, big guy."

"Greyhide chuckled, a deep, masculine rumble that sent Alexia’s tummy to tumbling again."

gh "I enjoy our foreplay. More than I ever expected to."

al " -And I enjoy {i}you{/i}, Greyhide."

"Greyhide chuckled again. He reached down and patted Alexia lovingly on the head."

gh "You’re an odd one, Alexia."
gh "...Are you satisfied now?"

show alexia necklace naked at midleft with dissolve

al "I am."

gh "Good."
gh "The delivery won't arrive for some hours yet. Enjoy your day off, for tomorrow we work."

al "...Are you sure you don’t need help?"

gh "What is there to help with? You have earned a break, I think."

"Alexia smiled at the old bull’s friendliness. She leaned up and planted a kiss on his cheek."

al "Thank you, Greyhide. This was a lot of fun."

"Greyhide let out a low grunt. He winked at her."

gh "You will have to teach me more."

return
