# descriptions for researches

init python:
    research_descriptions = {
        'world_and_the_war': "The world is ever shifting, ever changing.  Sometimes it does so more than others, but it always happens.  Even in the eternal forests of the elves.  When the dark lords rise is when the power of chaos is at its strongest and the face of the planet shifts with it.  Once that time ends, Solensia's power reasserts itself and things become fairly stable once more.\n\nAs the six realms recently finished the war against Karnas, things are still in a relative state of flux.  Determining the current state of affairs and the directions that each realm is taking will assist greatly in planning the twin's takeover.  Armed with this information, we will be capable of steering things in the direction we wish and have greater opportunities at our disposal.",
        'history_of_rosaria': "Rosaria is one of the human realms, steeped in tradition and the ebb and flow of its noble families.  There are nearly fifty such houses of various levels of prominence.  An extensive study of their family trees and accomplishments should assist when working in the upper circles of the realm's society.  We may also discover other useful bits of information including what artifacts can be found there, what creatures call it home, and resources can be exploited for the twin's benefit.",
        'military_tactics': "Our knowledge of military tactics and logistics is, rudimentary at best.  This makes it difficult to effectively manage fighting forces of any significant size and if we want to expand our ability to house troops we will need to change this.  An extensive study of military tactics will be the first step towards directly expanding our military capacities and is necessary if we want to upgrade any barracks we construct.\n\n I will be referencing things with Rowan as I do my work, as (at the time of writing) he is not only the most experienced general in the entire castle, he is the only one with any true fighting experience in a leadership role.  The orc clan leader we did have was among the casualties during the diversionary attack at Arthdale.",
        'survivalism_and_cartography': "While Rowan has exceptional skill in travelling through rough terrain, hunting, and passing by enemy forces undetected, his reported maps have, thus far, left a great deal to be desired.  He also seems to have been self taught, so there are likely some tricks unknown to him that can be gleaned from studying survivalism.  Once given the go ahead, I will begin putting together a crash course in survivalism and cartography that should greatly improve his efficiency in the field.",
        'surveying_and_telescopics': "The use of telescopes would be of great assistance to speeding the surveying of territory.  It will allow Rowan and any other exploration teams to get a better understanding of their surrounding terrain from a distance.  Once given the go ahead, I will arrange for the equipment required to make these devices to be delivered here and will begin assembling them.  As telescopic lenses will be of use to my own research, I do not mind paying the cost of the supplies myself.",
        'monster_taming': "In addition to their armies of chaos races, demon lords have traditionally also used horrific monsters in their armies.  These range from the smaller driders and manticores to the larger trolls and tentacle beasts, and also includes the legendary creatures like (dragon name?) and (other legendary monster).  Other creatures are popular among many of the chaotic races as mounts and this line of research will also give us the knowledge needed to construct infrastructure for supporting such mounted forces.\n\nThe twins have expressed a perhaps unhealthy interest in pursuing this line of bolstering their forces.  If we are to continue on this path, I will need to catalogue an overview on previous monster taming techniques and determine the basics of constructing facilities to house monsters.  The one saving grace is that Jezera has assured me that she will have no problems transporting creatures of any size in and out of the castle, given some time to work and a suitable portal in what will become the breeding pit.",
        'opulence': "Each new race brought into the fold increases the tensions and difficulties in managing the rest.  Further expansion of the castle halls and surface structure will be absolutely necessary to keep all in line and eager to die for the twin's causes.  I will be working closely with Skordred as we determine the path forward for reconstruction and further restoration for Bloodmeen.  Jezera has mentioned that this will also give her a chance to improve the surface infrastructure.",
        'dark_subterfuge': "Jezera has insisted that I should preface this item as being high priority, though I don't see anything particularly special about espionage when you consider our overall situation.\n\n At any rate, we are now in a position where we can seriously consider building facilities to support a small team of spies in the castle.  The natural candidates for this work will be particularly talented incubi and succubi.  They will offer the opportunity to take more subtle tactics to secure new territory and means of directly gathering intelligence on the six realms instead of relying on rumors and hearsay.",
        'contact_network': "While the facilities in the castle are quite impressive, it is impossible to find everything that one might need for magical and research pursuits in one place.  Therefore I would like to request permission to spend some time traveling around the world in order to establish a contact network that I can use to get any supplies or books I'm missing here.  This will be necessary if we have any intention of expanding my operations in the library, which in turn will be necessary when it comes time to expand the magical branch of the army beyond a limited force.",
        'basic_summoning': "Bolstering the castle's forces with entities conjured out of the primal elements offers two primary benefits.  First of all, these elementals are easily replaced and essentially create a basic amount of military power that the twins will always have access to.  It will also lead into other techniques that can be used to take further advantage of conquests by converting fallen enemies into undead through necromancy, or by sacrificing those taken alive through demonology.",
        'smelting': "During the last war a great innovation spread across the six realms that is likely one of the main contributing factors towards Karnas's defeat.  That is, the new technique of smelting iron.  It is my understanding that a new alloy, steel, becomes possible to make using this.  While it will take further work to determine how to produce this new metal, an extensive study of smelting will allow us to improve our existing forge facilities.  However, this knowledge will not do the twins any good until a forge has been built for the castle.",
        'fiendish_diplomacy': "Bringing more of the chaos races under the banner of the twins will require diplomacy.  Based on my historical studies, the best place to start will be by creating an impressive and opulent castle.  All races almost invariably respect the biggest and strongest, therefore the more powerful we appear to be, the more attractive we will be as an alliance partner.  The forces that have already been recruited are also more likely to remain loyal if we appear stronger.\n\nIn addition, Jezera has insisted that I also take this opportunity to do research into recruiting a cadre of lesser demons to serve as agents.  Though I don't see anything particularly special about espionage when you consider our overall situation, I will indulge her.\n\nThe natural candidates for this work will be particularly talented incubi and succubi.  They will offer the opportunity to take more subtle tactics to secure new territory and means of directly gathering intelligence on the six realms instead of relying on rumors and hearsay.  There is no doubt that these spies would also be of great help in both our diplomatic efforts with chaos races.",
        'silks_and_smiles': "As our cloak and dagger activities dealing with the six realms expand, so too must our methods and infrastructure.  Research is to be done in order to locate potential sites for additional taverns for gathering information, nests for our spies to operate from, as well as inspirations for additional comforts.\n\nThese upgrades will likely be excessive, however our mistress is a woman of excess and I must oblige her.  Fortunately it will give me some opportunities to work on integrating the castle spy network with my own which will allow us to interview additional potential spies when recruiting.",
        'ordering_chaos': "The current forces of the fortress are little more than a raiding party at best, and an undisciplined mob at worst.  While Rowan is a tactical genius, he has never before led anything like orcs before, which require radically different talents and methods.  The master Andras has some talent for it, but is untrained, untested, and unruly.  It will take time and effort from both myself and Rowan to turn Bloodmeens orcs into a true fighting force.",
        'military_logistics': "Our applications of military tactics and logistics are rudimentary at best.  This makes it difficult to effectively manage fighting forces of any significant size and if we want to expand our ability to house troops we will need to change this.  An extensive study of military operations will be the next step towards directly expanding our military capacities and is necessary if we want to maintain forces of serious size in the castle.\n\nI will be referencing things with Rowan as I do my work, as (at the time of writing) he is not only the most experienced general in the entire castle, he is the only one with any true fighting experience in a leadership role.  The orc clan leader we did have was among the casualties during the diversionary attack at Arthdale.",
        'research_infrastructure': "There remains much to be done to improve and repair the library and laboratories in the castle.  Now is the time to do a full inventory on what remains and can be salvaged from before the war.  I will take this opportunity to also catalogue a list of improvements and compare our knowledge to that of the facilities owned by my network of contacts.",
        'advanced_telescopics': "",
        "military_recreation": "",
        "monster_zoology": "",
        "special_handling_techniques": "",
    }

    research_reports = {
        'world_and_the_war': "The six realms are spread out to the South and East of castle Bloodmeen and the Rackshan Wastes it unofficially rules over.  In the South, the main realms are the Forest of Ealoaen, then Rosaria, followed by the Frozen Tundra.  To the East are the Empire of Sand and the Dragon's Tail.   Lastly, in the center of them all, is the Holy City of Prothea and its small dominance.\n\n\
For the most part, the years after the war have been that of peace and rebuilding, though there are always some machinations of the ambitious and petty.  However, these squabbles have been limited to internal realm struggles.  There are currently no open hostilities between any of the six realms.  Similarly, there are no official alliances or pacts between any realms, save with Prothea.  The other five realms pay at least some form of tribute to Prothea and recognize it as their final religious authority.  Rosaria has the strongest ties, being the one closest to the Holy City geographically.\n\n\
All of the realms are still dealing with the remnants of Karnas's armies as well as various crises and distractions.  As each is primarily concerned with internal affairs, now is an excellent time to gather strength in preparation to move against them.  Until we play our hand and actually invade or turn a realm to our side, it is extremely unlikely that any of them will take steps to undermine us as a united force.\n\n\
If directed, I may continue these studies with a more focused study on any of the Six Realms.\n\n\
More specific reports about each realm you may visit are now available to you in the Throne room.  These will be regularly updated with any new information gathered from our agents.  New options have been unlocked in events.",
        'history_of_rosaria': "Landscape - The primary terrain is arable land, with smaller patches of wooded land, swamp, and hills. The main exception is the large forest, the Blackholt Woods, in the east of the realm. From its source high in the mountains of the East, the river Yael runs east through Rastedel, before splitting into two main tributaries; one flowing further west to the sea, the other heading south to disappear under the Broken Mountains. In the north, the Rosarian valley cuts across the realm, separating the lower part from the Holy Kingdom of Prothea further north, and the giant trees of the Forest of Eoloaen.\n\n\
Demographics - The population of Rosaria is largely human, and for the most part the work in industries that benefit the feudal society; either as farmers, or as blacksmiths, potters, crofters, and other tradesmen. More adventurous humans may become travelling salesmen,  or soldiers serving the barony, while the reckless or brave may take up adventuring or monster hunting.  Rarer, but still a common sight in the larger towns are the half-elven, those whose ancestry is at some point tinged with elven blood, and who have, either as the result of choice or by an accident of birth, opted to live outside the darkness of Eoloaen. Much rarer are the pure elven, who rarely venture outside the forest, consumed by the war with their dark brethren, and the drakken (the dragon equivalent of the half elven). Real dragons are so rare that most people in Rosaria (wrongly) think they are extinct.\n\n\
Threats - Due to a poor harvest, banditry is on the rise once again, with rumours have begun to spread of a particularly nasty group hiding out in the western forest. In the north, a savage orc warchief , having broken his alliance with the dark elves and quit the great forest, is amusing himself raiding the local villages. The story of demons destroying a village making its way through the realm has also increased the activity of cultists, and others who seek power through the dark arts. The countryside is also littered with less organized threats, like lone ogres who wander out from the Broken Mountains in search of food, bloody thirsty trolls, the restless dead, and other monsters small and large.\n\n\
Finally, I've prepared a list of all the Rosarian noble houses, the current state of each, and their accomplishments during the last war.  It should be of use to Rowan when dealing with the nobility while he is in Rosaria.\n\n\
New information has been added to the Rosaria realm report.  New options have been unlocked in events.",
        'military_tactics': "While Andras's reluctance to let anyone tell him what to do makes teaching him difficult, he is at least willing to listen to sense and logic when pressured.  The combined efforts of myself and Rowan have produced results, turning the army underneath us from an undisciplined mob into something that can function with at least some cohesion.\n\n\
Further efforts will be needed to turn this force into an actual professional army, but at the very least the facilities can now be expanded to hold a larger force without fear of that force tearing itself apart.  The next step will be improving our logistics.\n\n\
Level 2 Orc Barracks unlocked.",
        'survivalism_and_cartography': "I refuse to continue attempting to educate Rowan in the field of survivalism.  I am no longer comfortable in this line of work.  He has been taught how to draw a proper map, I will leave it at that.  If further work is necessary, a new teacher will have to be brought in.\n\n Your movement points while exploring have been increased by 1.",
        'surveying_and_telescopics': "A set of telescopes and other surveying equipment, as well as a few backups, are now prepared.  I will give a brief overview on their use and provide them to Rowan at the first opportunity.\n\n\
Your visibility range while exploring has been increased by 1.",
        'monster_taming': "I have finished preparing plans for constructing a facility for both breeding and storing monsters.  Currently our understanding is only enough to handle the smaller monsters, such as driders.  More studies will be needed if we wish to add larger creatures to our forces.  I will once again advise caution when using these beasts, as they are difficult to control and very dangerous.  It will be wise not to rely on them too extensively.\n\n\
Level 1 Breeding Pit unlocked.\n\
Level 1 Warg Kennel unlocked.",
        'opulence': "We have recovered or restored nearly all of the original construction plans for the castle now.  Skordred has been ecstatic to have had my help in this endeavor and is eager to continue expanding the castle.  The grander it becomes, the more loyal the followers will become.  Do be aware that there will also be greater upkeep costs for each expansion and proper precautions should be taken before such investments are made.\n\n\
Level 3 Castle Hall/Throne Room",
        'dark_subterfuge': "The basics of the arts of cubi espionage and infiltration are now ours.  Due to the somewhat petty nature of these succubi and incubi that will be serving as the castle's wing of shadow operatives, we will need to construct a special facility for them before we begin recruiting.  The plans have been prepared, and I'm sure that Jezera will be ecstatic when she learns that construction has begun.\n\n\
Level 1 Brothel unlocked.",
        'contact_network': "I am pleased to report my success in establishing a suitable contact network throughout the Six Realms.  As of this moment, our magic users will be well supplied with basic magical reagents should they need to enter battle.  Personally I am now in a position where I can see to the expansion of our existing library and magical facilities, in order to have space for more staff, books, alchemical supplies, and magical implements.  Skordred has been briefed on my requirements and is prepared to oversee the expansionary work once ordered and provided the necessary funds.\n\n\
Level 2 Library unlocked.",
        'basic_summoning': "Thanks to my network of contacts, I've managed to locate a suitable expert in the arts of summoning that has agreed to join us in the castle once we've finished constructing a proper summoning chamber for him to take up residence.  The twins have already met with him and given their approval for the construction plans he has provided.\n\n\
Level 1 Summoning Chamber unlocked.",
        'smelting': "I've determined a new form of air pump that will allow us to make much larger and hotter forges.  This will allow us to upgrade any existing forges to a larger size and I will be able to follow up on this research to determine the metallurgic components of steel.  After all, we can now make a hot enough forge to actually smelt the metal alloy.\n\n\
Level 2 Forge unlocked.",
        'fiendish_diplomacy': "They say that pride comes before fall, but without pride we will never rise in the first place.  Skordred and I have now finished plans to expand and reclaim more of the surface region of the castle as well as prepare proper facilities for our cadre of cubi spies.  Due to the somewhat petty nature of these succubi and incubi that will be serving as the castle's wing of shadow operatives, we will need to construct a special facility for them before we begin recruiting.  He is standing by to begin work as soon as the funds are allocated for such a project and I'm sure that Jezera will be ecstatic when she learns that construction has begun.\n\n\
New building unlocked: Brothel Level 1\n\
Level 2 Castle Hall unlocked.",
        'silks_and_smiles': "I have finished compiling my report on potential site expansions for taverns and spy nests.  I have included several worthwhile upgrades to the existing tavern that Indarah has requested.  In terms of immediate benefits, our recruitment capacity for spies has already increased and will give you more flexibility when selecting new spies to add to our roster.\n\n\
Bonus: +1 option when recruiting spies\n\
Level 2 Tavern unlocked.\n\
Level 2 Brothel unlocked.",
        'ordering_chaos': "While Andras's reluctance to let anyone tell him what to do makes teaching him difficult, he is at least willing to listen to sense and logic when pressured.  The combined efforts of myself and Rowan have produced results, turning the army underneath us from an undisciplined mob into something that can function with at least some cohesion.\n\nFurther efforts will be needed to turn this force into an actual professional army, but at the very least the facilities can now be expanded to hold a larger force without fear of that force tearing itself apart.  The next step will be improving our logistics.\n\n\
Bonus: +1 base military power for orc soldiers\n\
Level 1 Arena unlocked.\n\
Level 2 Barracks unlocked.",
        'military_logistics': "A typical orc only cares about a handful of simple things.  Fighting, sex, and spoils.  In many respects, they are the truest of the chaos races.  We must use these motivators and a certain degree of awe to bring any of them under proper military discipline.  As that capacity rises, we will find other limiting factors start to arise instead, which must be addressed in turn.  In this case, those are proper supply lines for keeping all the soldiers fed, a rudimentary command hierarchy of officers, and a somewhat more varied set of entertainment options.\n\n\
Level 3 Orc Barracks unlocked.\n\
Level 2 Arena unlocked.",
        'research_infrastructure': "The majority of my reports on both our salvageable magic resources and potential improvements have been passed onto Skordred.  The details are likely beyond you, suffice it to say that the castle is quite the treasure trove, assuming we have the funds needed to set everything into order once more.\n\n\
Level 3 Library unlocked.",
        'advanced_telescopics': "",
        "military_recreation": "",
        "special_handling_techniques": "",
    }

    research_requires = {
        "survivalism_and_cartography": [],
        "surveying_and_telescopics": ["Requires technology: Survivalism and Cartography"],
        "fiendish_diplomacy": [],
        "opulence": ["Requires technology: Fiendish Diplomacy", "Requires building: Castle Hall lv 2"],
        "silks_and_smiles": ["Requires technology: Fiendish Diplomacy", "Requires either building: Brothel lv 1 OR Tavern lv 1"],
        "ordering_chaos": [],
        "military_logistics": ["Requires technology: Ordering Chaos", "Requires either building: Orc Barracks lv 2 or Arena lv 1"],
        "contact_network": [],
        "research_infrastructure": ["Requires technology: Contact Network", "Requires either building: Library lv 2 OR Dark Sanctum lv 1"],
        "monster_taming": [],
        "smelting": ["Requires building: Forge lv 1"],
        "advanced_telescopics": ["Requires Technology: Surveying and Telescopics"],
        "military_recreation": [],
        "monster_zoology": [],
        "special_handling_techniques": [],
    }

    research_bonus = {
        "survivalism_and_cartography": ["Bonus: +1 movement point on map"],
        "surveying_and_telescopics": ["Bonus: +1 sight range on map"],
        "fiendish_diplomacy": ["New building unlocked: Brothel lv 1", "Upgrade unlocked: Castle Hall lv 2"],
        "opulence": ["Upgrade unlocked: Castle Hall lv 3"],
        "silks_and_smiles": ["Bonus: +1 option when recruiting spies", "Upgrade unlocked: Tavern lv 2", "Upgrade unlocked: Brothel lv 2"],
        "ordering_chaos": ["Bonus: +1 base military power for orc soldiers", "New building unlocked: Arena lv 1", "Upgrade unlocked: Orc Barracks lv 2"],
        "military_logistics": ["Upgrade unlocked: Orc Barracks lv 3", "Upgrade unlocked: Arena lv 2"],
        "contact_network": ["Upgrade unlocked: Library lv 2"],
        "research_infrastructure": ["Upgrade unlocked: Library lv 3", "Upgrade unlocked: Dark Sanctum lv 2"],
        "monster_taming": ["New building unlocked: Breeding Pits lv 1", "New building unlocked: Warg Kennel lv 1"],
        "smelting": ["Upgrade unlocked: Forge lv 2"],
        "advanced_telescopics": ["Increases visible hex range to 3."],
        "military_recreation": [],
        "monster_zoology": [],
}
